// Source: https://gist.github.com/sam016/4abe921b5a9ee27f67b3686910293026
class Characteristics {
  Characteristics._();

  static const String bluetoothBaseUuidSuffix = '-0000-1000-8000-00805f9b34fb';

  static const Map<int, String> names = {
    0x2a00: 'Device Name',
    0x2a01: 'Appearance',
    0x2a02: 'Peripheral Privacy Flag',
    0x2a03: 'Reconnection Address',
    0x2a04: 'Peripheral Preferred Connection Parameters',
    0x2a05: 'Service Changed',
    0x2a06: 'Alert Level',
    0x2a07: 'Tx Power Level',
    0x2a08: 'Date Time',
    0x2a09: 'Day of Week',
    0x2a0a: 'Day Date Time',
    0x2a0b: 'Exact Time 100',
    0x2a0c: 'Exact Time 256',
    0x2a0d: 'DST Offset',
    0x2a0e: 'Time Zone',
    0x2a0f: 'Local Time Information',
    0x2a10: 'Secondary Time Zone',
    0x2a11: 'Time with DST',
    0x2a12: 'Time Accuracy',
    0x2a13: 'Time Source',
    0x2a14: 'Reference Time Information',
    0x2a15: 'Time Broadcast',
    0x2a16: 'Time Update Control Point',
    0x2a17: 'Time Update State',
    0x2a18: 'Glucose Measurement',
    0x2a19: 'Battery Level',
    0x2a1a: 'Battery Power State',
    0x2a1b: 'Battery Level State',
    0x2a1c: 'Temperature Measurement',
    0x2a1d: 'Temperature Type',
    0x2a1e: 'Intermediate Temperature',
    0x2a1f: 'Temperature Celsius',
    0x2a20: 'Temperature Fahrenheit',
    0x2a21: 'Measurement Interval',
    0x2a22: 'Boot Keyboard Input Report',
    0x2a23: 'System ID',
    0x2a24: 'Model Number String',
    0x2a25: 'Serial Number String',
    0x2a26: 'Firmware Revision String',
    0x2a27: 'Hardware Revision String',
    0x2a28: 'Software Revision String',
    0x2a29: 'Manufacturer Name String',
    0x2a2a: 'IEEE 11073-20601 Regulatory Certification Data List',
    0x2a2b: 'Current Time',
    0x2a2c: 'Magnetic Declination',
    0x2a2f: 'Position 2D',
    0x2a30: 'Position 3D',
    0x2a31: 'Scan Refresh',
    0x2a32: 'Boot Keyboard Output Report',
    0x2a33: 'Boot Mouse Input Report',
    0x2a34: 'Glucose Measurement Context',
    0x2a35: 'Blood Pressure Measurement',
    0x2a36: 'Intermediate Cuff Pressure',
    0x2a37: 'Heart Rate Measurement',
    0x2a38: 'Body Sensor Location',
    0x2a39: 'Heart Rate Control Point',
    0x2a3a: 'Removable',
    0x2a3b: 'Service Required',
    0x2a3c: 'Scientific Temperature Celsius',
    0x2a3d: 'String',
    0x2a3e: 'Network Availability',
    0x2a3f: 'Alert Status',
    0x2a40: 'Ringer Control point',
    0x2a41: 'Ringer Setting',
    0x2a42: 'Alert Category ID Bit Mask',
    0x2a43: 'Alert Category ID',
    0x2a44: 'Alert Notification Control Point',
    0x2a45: 'Unread Alert Status',
    0x2a46: 'New Alert',
    0x2a47: 'Supported New Alert Category',
    0x2a48: 'Supported Unread Alert Category',
    0x2a49: 'Blood Pressure Feature',
    0x2a4a: 'HID Information',
    0x2a4b: 'Report Map',
    0x2a4c: 'HID Control Point',
    0x2a4d: 'Report',
    0x2a4e: 'Protocol Mode',
    0x2a4f: 'Scan Interval Window',
    0x2a50: 'PnP ID',
    0x2a51: 'Glucose Feature',
    0x2a52: 'Record Access Control Point',
    0x2a53: 'RSC Measurement',
    0x2a54: 'RSC Feature',
    0x2a55: 'SC Control Point',
    0x2a56: 'Digital',
    0x2a57: 'Digital Output',
    0x2a58: 'Analog',
    0x2a59: 'Analog Output',
    0x2a5a: 'Aggregate',
    0x2a5b: 'CSC Measurement',
    0x2a5c: 'CSC Feature',
    0x2a5d: 'Sensor Location',
    0x2a5e: 'PLX Spot-Check Measurement',
    0x2a5f: 'PLX Continuous Measurement Characteristic',
    0x2a60: 'PLX Features',
    0x2a62: 'Pulse Oximetry Control Point',
    0x2a63: 'Cycling Power Measurement',
    0x2a64: 'Cycling Power Vector',
    0x2a65: 'Cycling Power Feature',
    0x2a66: 'Cycling Power Control Point',
    0x2a67: 'Location and Speed Characteristic',
    0x2a68: 'Navigation',
    0x2a69: 'Position Quality',
    0x2a6a: 'LN Feature',
    0x2a6b: 'LN Control Point',
    0x2a6c: 'Elevation',
    0x2a6d: 'Pressure',
    0x2a6e: 'Temperature',
    0x2a6f: 'Humidity',
    0x2a70: 'True Wind Speed',
    0x2a71: 'True Wind Direction',
    0x2a72: 'Apparent Wind Speed',
    0x2a73: 'Apparent Wind Direction',
    0x2a74: 'Gust Factor',
    0x2a75: 'Pollen Concentration',
    0x2a76: 'UV Index',
    0x2a77: 'Irradiance',
    0x2a78: 'Rainfall',
    0x2a79: 'Wind Chill',
    0x2a7a: 'Heat Index',
    0x2a7b: 'Dew Point',
    0x2a7d: 'Descriptor Value Changed',
    0x2a7e: 'Aerobic Heart Rate Lower Limit',
    0x2a7f: 'Aerobic Threshold',
    0x2a80: 'Age',
    0x2a81: 'Anaerobic Heart Rate Lower Limit',
    0x2a82: 'Anaerobic Heart Rate Upper Limit',
    0x2a83: 'Anaerobic Threshold',
    0x2a84: 'Aerobic Heart Rate Upper Limit',
    0x2a85: 'Date of Birth',
    0x2a86: 'Date of Threshold Assessment',
    0x2a87: 'Email Address',
    0x2a88: 'Fat Burn Heart Rate Lower Limit',
    0x2a89: 'Fat Burn Heart Rate Upper Limit',
    0x2a8a: 'First Name',
    0x2a8b: 'Five Zone Heart Rate Limits',
    0x2a8c: 'Gender',
    0x2a8d: 'Heart Rate Max',
    0x2a8e: 'Height',
    0x2a8f: 'Hip Circumference',
    0x2a90: 'Last Name',
    0x2a91: 'Maximum Recommended Heart Rate',
    0x2a92: 'Resting Heart Rate',
    0x2a93: 'Sport Type for Aerobic and Anaerobic Thresholds',
    0x2a94: 'Three Zone Heart Rate Limits',
    0x2a95: 'Two Zone Heart Rate Limit',
    0x2a96: 'VO2 Max',
    0x2a97: 'Waist Circumference',
    0x2a98: 'Weight',
    0x2a99: 'Database Change Increment',
    0x2a9a: 'User Index',
    0x2a9b: 'Body Composition Feature',
    0x2a9c: 'Body Composition Measurement',
    0x2a9d: 'Weight Measurement',
    0x2a9e: 'Weight Scale Feature',
    0x2a9f: 'User Control Point',
    0x2aa0: 'Magnetic Flux Density - 2D',
    0x2aa1: 'Magnetic Flux Density - 3D',
    0x2aa2: 'Language',
    0x2aa3: 'Barometric Pressure Trend',
    0x2aa4: 'Bond Management Control Point',
    0x2aa5: 'Bond Management Features',
    0x2aa6: 'Central Address Resolution',
    0x2aa7: 'CGM Measurement',
    0x2aa8: 'CGM Feature',
    0x2aa9: 'CGM Status',
    0x2aaa: 'CGM Session Start Time',
    0x2aab: 'CGM Session Run Time',
    0x2aac: 'CGM Specific Ops Control Point',
    0x2aad: 'Indoor Positioning Configuration',
    0x2aae: 'Latitude',
    0x2aaf: 'Longitude',
    0x2ab0: 'Local North Coordinate',
    0x2ab1: 'Local East Coordinate',
    0x2ab2: 'Floor Number',
    0x2ab3: 'Altitude',
    0x2ab4: 'Uncertainty',
    0x2ab5: 'Location Name',
    0x2ab6: 'URI',
    0x2ab7: 'HTTP Headers',
    0x2ab8: 'HTTP Status Code',
    0x2ab9: 'HTTP Entity Body',
    0x2aba: 'HTTP Control Point',
    0x2abb: 'HTTPS Security',
    0x2abc: 'TDS Control Point',
    0x2abd: 'OTS Feature',
    0x2abe: 'Object Name',
    0x2abf: 'Object Type',
    0x2ac0: 'Object Size',
    0x2ac1: 'Object First-Created',
    0x2ac2: 'Object Last-Modified',
    0x2ac3: 'Object ID',
    0x2ac4: 'Object Properties',
    0x2ac5: 'Object Action Control Point',
    0x2ac6: 'Object List Control Point',
    0x2ac7: 'Object List Filter',
    0x2ac8: 'Object Changed',
    0x2ac9: 'Resolvable Private Address Only',
    0x2acc: 'Fitness Machine Feature',
    0x2acd: 'Treadmill Data',
    0x2ace: 'Cross Trainer Data',
    0x2acf: 'Step Climber Data',
    0x2ad0: 'Stair Climber Data',
    0x2ad1: 'Rower Data',
    0x2ad2: 'Indoor Bike Data',
    0x2ad3: 'Training Status',
    0x2ad4: 'Supported Speed Range',
    0x2ad5: 'Supported Inclination Range',
    0x2ad6: 'Supported Resistance Level Range',
    0x2ad7: 'Supported Heart Rate Range',
    0x2ad8: 'Supported Power Range',
    0x2ad9: 'Fitness Machine Control Point',
    0x2ada: 'Fitness Machine Status',
    0x2aed: 'Date UTC',
    0x2b1d: 'RC Feature',
    0x2b1e: 'RC Settings',
    0x2b1f: 'Reconnection Configuration Control Point',
  };

  static String lookup(String uuid, {String defaultName = '--'}) {
    final normalizedUuid = uuid.toLowerCase();
    if (normalizedUuid.length != 36 ||
        !normalizedUuid.startsWith('0000') ||
        !normalizedUuid.endsWith(bluetoothBaseUuidSuffix)) {
      return defaultName;
    }

    final assignedNumber = int.tryParse(
      normalizedUuid.substring(4, 8),
      radix: 16,
    );
    return names[assignedNumber] ?? defaultName;
  }

  static String uuid(int assignedNumber) {
    return '0000${assignedNumber.toRadixString(16).padLeft(4, '0')}$bluetoothBaseUuidSuffix';
  }
}
